In [2]:
import torch


In [3]:
x = torch.empty(5,3)
x

tensor([[-6.7607e-35,  7.5250e-43, -1.1500e-32],
        [ 7.5250e-43, -1.4837e-34,  7.5250e-43],
        [ 6.0797e+26,  0.0000e+00,  6.0797e+26],
        [ 0.0000e+00, -6.7607e-35,  7.5250e-43],
        [-1.1422e-32,  7.5250e-43, -1.1422e-32]])

In [57]:
x = torch.rand(5,3)


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [7]:
x = torch.ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.5350, -0.2687,  1.2667],
        [ 0.0697,  0.5338, -1.1063],
        [ 0.7710, -1.3307, -1.1858],
        [-1.0715, -0.1720, -1.6715],
        [-0.9848,  1.1993, -0.2656]])

In [9]:
x.size()

torch.Size([5, 3])

In [10]:
y = torch.rand(5,3)

In [11]:
%timeit x + y

4.36 µs ± 236 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%timeit torch.add(x,y)

4.01 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit y.add_(x)

1.33 µs ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
import numpy as np 

In [32]:
def add():
    x = np.random.rand(10000,10000)
    y = np.random.rand(10000,10000)
    return x + y

In [37]:
def add_cpu():
    device = torch.device('cpu')
    x = torch.rand(10000,10000, device=device)
    y = torch.rand(10000,10000, device=device)
    return x+y 

def add_cuda():
    device = torch.device('cuda')
    x = torch.rand(10000,10000, device=device)
    y = torch.rand(10000,10000, device=device)
    return x+y 

def add_torch():
    x = torch.rand(10000,10000)
    y = torch.rand(10000,10000)
    return x+y 

In [38]:
from numba import *

In [39]:
@jit
def add_jit():
    x = np.random.rand(10000,10000)
    y = np.random.rand(10000,10000)
    return x+y

In [53]:
torch.tensor.

TypeError: get_device() missing 1 required positional arguments: "input"

In [55]:
%time add_jit()
%time add_cuda()
%time add_cpu()
%time add()
%time add_torch()

Wall time: 3.8 s
Wall time: 1 ms
Wall time: 2.62 s
Wall time: 3.76 s
Wall time: 1e+03 µs


tensor([[1.1814, 0.8281, 0.4783,  ..., 0.5195, 1.5579, 0.1834],
        [0.5663, 1.7513, 0.8171,  ..., 0.6774, 1.3337, 0.3220],
        [1.8530, 0.7849, 0.3856,  ..., 1.6404, 0.3612, 1.5817],
        ...,
        [1.6618, 0.9158, 0.7430,  ..., 1.0217, 1.6030, 1.1447],
        [0.3129, 0.9783, 0.6536,  ..., 1.5256, 1.5361, 0.9459],
        [0.2374, 0.9951, 0.8966,  ..., 0.4706, 1.5017, 1.1517]])

In [48]:
x = torch.arange(0.,12.,1.)
%timeit x / 5

3.19 µs ± 357 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
x.to('cuda')
%timeit x/5

3.18 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
torch.set_default_tensor_type('torch.cuda.FloatTensor')
